Repository trkhduy/FE-UberEats, pull requests merged in 2023-05, with the labels that each got.

#1 building UI login
  package.json
  pages/index.tsx
  pages/user/login.tsx
  pages/user/register.tsx
  pages/user/style/login.module.scss
Labels: enhancement

#2 finish UI Login&Register
  package-lock.json
  pages/index.tsx
  pages/user/login.tsx
  pages/user/register.tsx
  pages/user/style/login.module.scss
  styles/Home.module.css
  styles/globals.css
Labels: enhancement

#4 FE/Fix layout
  modules/header.tsx
  pages/_app.tsx
Labels: bug

#8 T3FE01&T3FE03 update UI login and register
  pages/user/login.tsx
  pages/user/register.tsx
  pages/user/style/login.module.scss
Labels: bug

#9 T3FE08 Feat:FE/Build clien home page
  components/home.tsx
  components/home_client/home.tsx
  components/home_client/style/home.module.scss
  modules/header.tsx
  pages/index.tsx
  styles/layout/Footer.module.scss
  styles/layout/Header.module.scss
Labels: enhancement

#10 Fe/driver
  components/driver/index.tsx
  components/driver/style/home.module.scss
  components/restaurant_owner/listProcess.tsx
  package-lock.json
  package.json
  pages/driver/index.tsx
  pages/index.tsx
  styles/globals.css
  styles/layout/Header.module.scss
Labels: enhancement, good first issue

#12 T3FE15 FE/driver fest profileUI
  components/profile/profile.tsx
Labels: enhancement

#13 T3FE15 FE/driver fix profile
  components/layoutDriver.tsx
  components/profile/profile.tsx
  pages/_app.tsx
  pages/driver/profile.tsx
  pages/driver/statistics.tsx
  pages/user/style/login.module.scss
Labels: bug

#14 T3FE04 feat API integration for register page
  package-lock.json
  package.json
  pages/user/login.tsx
  pages/user/register.tsx
  service/config/axiosInstance.ts
  service/userService.tsx
Labels: enhancement

#16 T3FE12 Feat:FE/Build Cart page
  components/carousel_product/c_product.tsx
  components/carousel_product/style/c_product.module.scss
  components/home_client/style/home.module.scss
  modules/header.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/cart/index.tsx
  pages/cart/style/cart.module.scss
  pages/food/[id].tsx
  pages/food/index.tsx
  pages/food/style/detail.module.scss
  pages/food/style/shop.module.scss
  styles/layout/Footer.module.scss
  styles/layout/Header.module.scss
Labels: enhancement

#17 T3FE17 Feat:FE/Build client Order UI Page
  pages/cart/index.tsx
  pages/checkout/index.tsx
  pages/checkout/style/checkout.module.scss
Labels: enhancement

#18 Fix Ui Filter Food
  pages/food/index.tsx
Labels: bug

#21 Fe/api crud res
  components/home_client/style/home.module.scss
  modules/header.tsx
Labels: bug

#23 Fe/authorize router page
  pages/_app.tsx
  pages/user/login.tsx
Labels: enhancement

#24 Fe/api crud res
  components/profile/profile.tsx
  components/restaurant_owner/style/listOrder.module.scss
  modules/header.tsx
  next.config.js
  pages/_app.tsx
  pages/hook/useToken.tsx
  pages/restaurantowner/index.tsx
  pages/user/register.tsx
  service/config/axiosInstance.ts
  service/restaurantService.ts
  styles/layout/Header.module.scss
Labels: bug

#28 Fe/api crud food
  components/profile/profile.tsx
  components/restaurant_owner/listMenu.tsx
  components/restaurant_owner/modelProduct.tsx
  pages/restaurantowner/index.tsx
  pages/user/login.tsx
  pages/user/register.tsx
  service/config/axiosInstance.ts
  service/productService.ts
  service/restaurantService.ts
Labels: enhancement

#29 Fe/api crud res
  components/profile/profile.tsx
  pages/restaurantowner/index.tsx
  pages/user/style/login.module.scss
  service/restaurantService.ts
Labels: bug, enhancement

#30 Fix loi profile
  components/profile/profile.tsx
Labels: bug

#31 Fe/api client home
  components/profile/profile.tsx
  modules/header.tsx
  service/productService.ts
  service/userService.ts
Labels: enhancement

#32 Fe/api crud food
  components/profile/profile.tsx
  components/restaurant_owner/listCategory.tsx
  components/restaurant_owner/listMenu.tsx
  components/restaurant_owner/listVoucher.tsx
  components/restaurant_owner/modelCategory.tsx
  components/restaurant_owner/modelVoucher.tsx
  pages/restaurantowner/index.tsx
  service/restaurantService.ts
  styles/globals.css
Labels: enhancement

#33 T3FE22 T3FE21 Feat:FE/Api-itegrate-home-client
  components/home_client/home.tsx
  components/home_client/style/home.module.scss
  components/profile/profile.tsx
  modules/header.tsx
  service/clientService.ts
  service/restaurantService.ts
  service/userService.ts
  styles/layout/Header.module.scss
Labels: bug, enhancement

#34 FE/Update api- refresh token
  components/home_client/style/home.module.scss
  modules/header.tsx
  service/config/axiosInstance.ts
Labels: bug

#35 T3FE29 Feat:FE/Api-integrate-client-food-page
  pages/food/index.tsx
  service/clientService.ts
Labels: enhancement

#36 Fe/cart
  components/home_client/home.tsx
  components/profile/profileDriver.tsx
  modules/header.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/cart/index.tsx
  pages/cart/style/cart.module.scss
  pages/driver/profile.tsx
  pages/user/login.tsx
  redux/reducer/cartReducer.ts
  redux/store.ts
  service/cartService.ts
  service/userService.ts
Labels: enhancement

#37 T3FE31 Feat:FE/api integrate detail food page
  components/home_client/home.tsx
  pages/food/[id].tsx
  pages/food/index.tsx
  service/clientService.ts
Labels: enhancement

#38 T3FE32 Feat:FE/api integrate client profile
  components/driver/style/home.module.scss
  components/home_client/home.tsx
  components/home_client/modalUserAddress.tsx
  components/home_client/style/home.module.scss
  components/profile/profileClient.tsx
  modules/header.tsx
  pages/cart/index.tsx
  pages/cart/style/cart.module.scss
  pages/checkout/style/checkout.module.scss
  pages/food/[id].tsx
  pages/food/index.tsx
  pages/food/style/detail.module.scss
  pages/food/style/shop.module.scss
  pages/user/profile.tsx
  service/userService.ts
  styles/layout/Header.module.scss
  styles/restaurant/restaurant.module.scss
Labels: enhancement
